"""table updated

Revision ID: 0242fe927739
Revises: a89c973778bf
Create Date: 2021-04-14 13:01:02.987894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0242fe927739'
down_revision = 'a89c973778bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'address', ['building_number'])
    op.drop_constraint('address_barber_shop_id_fkey', 'address', type_='foreignkey')
    op.create_foreign_key(None, 'address', 'barber_shop', ['barber_shop_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.create_foreign_key('address_barber_shop_id_fkey', 'address', 'barber_shop', ['barber_shop_id'], ['id'])
    op.drop_constraint(None, 'address', type_='unique')
    # ### end Alembic commands ###
