"""Tables created

Revision ID: 0dec618c23d6
Revises: 
Create Date: 2021-04-12 13:59:55.785378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dec618c23d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barber_shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barber_shop_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('city', sa.String(length=40), nullable=False),
    sa.Column('street_name', sa.String(length=40), nullable=False),
    sa.Column('building_number', sa.String(length=20), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['barber_shop_id'], ['barber_shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('barbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barber_shop_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('haircut', sa.Boolean(), nullable=False),
    sa.Column('beardcut', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['barber_shop_id'], ['barber_shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('barbers')
    op.drop_table('address')
    op.drop_table('client')
    op.drop_table('barber_shop')
    # ### end Alembic commands ###
