"""password to hash

Revision ID: 345f470eba7c
Revises: 1f4a2cf0293a
Create Date: 2021-04-16 12:03:04.556850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345f470eba7c'
down_revision = '1f4a2cf0293a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('barber_shop', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('client', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('barber_shop', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
