"""Table services created

Revision ID: 378c61d5b94e
Revises: 0dec618c23d6
Create Date: 2021-04-12 14:47:19.227864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378c61d5b94e'
down_revision = '0dec618c23d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=40), nullable=False),
    sa.Column('service_price', sa.String(length=4), nullable=False),
    sa.Column('barber_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['barber_id'], ['barbers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_name'),
    sa.UniqueConstraint('service_price')
    )
    op.drop_column('barbers', 'haircut')
    op.drop_column('barbers', 'beardcut')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barbers', sa.Column('beardcut', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('barbers', sa.Column('haircut', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_table('services')
    # ### end Alembic commands ###
