"""Tables updated

Revision ID: 7307a432a973
Revises: 7b88500c85f7
Create Date: 2021-04-13 16:10:58.388766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7307a432a973'
down_revision = '7b88500c85f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barber_shop', sa.Column('user_type', sa.String(length=10), nullable=False))
    op.add_column('barbers', sa.Column('user_type', sa.String(length=10), nullable=False))
    op.add_column('client', sa.Column('user_type', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'user_type')
    op.drop_column('barbers', 'user_type')
    op.drop_column('barber_shop', 'user_type')
    # ### end Alembic commands ###
