"""Table Appointments create

Revision ID: 7b88500c85f7
Revises: 378c61d5b94e
Create Date: 2021-04-12 17:59:57.239133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b88500c85f7'
down_revision = '378c61d5b94e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barber_id', sa.Integer(), nullable=False),
    sa.Column('services_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['barber_id'], ['barbers.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['services_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'barber_shop', ['cnpj'])
    op.drop_constraint('client_name_key', 'client', type_='unique')
    op.drop_constraint('services_service_name_key', 'services', type_='unique')
    op.drop_constraint('services_service_price_key', 'services', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('services_service_price_key', 'services', ['service_price'])
    op.create_unique_constraint('services_service_name_key', 'services', ['service_name'])
    op.create_unique_constraint('client_name_key', 'client', ['name'])
    op.drop_constraint(None, 'barber_shop', type_='unique')
    op.drop_table('appointments')
    # ### end Alembic commands ###
