"""table created

Revision ID: a89c973778bf
Revises: 6427360b0479
Create Date: 2021-04-13 20:31:25.577092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89c973778bf'
down_revision = '6427360b0479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('barber_shop_id', sa.Integer(), nullable=True))
    op.drop_constraint('address_barber_shop_name_key', 'address', type_='unique')
    op.drop_constraint('address_barber_shop_name_fkey', 'address', type_='foreignkey')
    op.create_foreign_key(None, 'address', 'barber_shop', ['barber_shop_id'], ['id'])
    op.drop_column('address', 'barber_shop_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('barber_shop_name', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.create_foreign_key('address_barber_shop_name_fkey', 'address', 'barber_shop', ['barber_shop_name'], ['name'])
    op.create_unique_constraint('address_barber_shop_name_key', 'address', ['barber_shop_name'])
    op.drop_column('address', 'barber_shop_id')
    # ### end Alembic commands ###
