"""added barber shop id to appointments

Revision ID: cc5f90996ebd
Revises: 7307a432a973
Create Date: 2021-04-13 16:27:51.671174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc5f90996ebd'
down_revision = '7307a432a973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('barber_shop_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'appointments', 'barber_shop', ['barber_shop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'barber_shop_id')
    # ### end Alembic commands ###
