"""adicionado onupdate e ondelete no appointments model

Revision ID: cfae44913ec7
Revises: 7b88500c85f7
Create Date: 2021-04-13 12:32:20.473380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfae44913ec7'
down_revision = '7b88500c85f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('appointments_client_id_fkey', 'appointments', type_='foreignkey')
    op.drop_constraint('appointments_services_id_fkey', 'appointments', type_='foreignkey')
    op.drop_constraint('appointments_barber_id_fkey', 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'services', ['services_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'client', ['client_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'barbers', ['barber_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key('appointments_barber_id_fkey', 'appointments', 'barbers', ['barber_id'], ['id'])
    op.create_foreign_key('appointments_services_id_fkey', 'appointments', 'services', ['services_id'], ['id'])
    op.create_foreign_key('appointments_client_id_fkey', 'appointments', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###
