"""address unique to false

Revision ID: fafc3dde8627
Revises: 345f470eba7c
Create Date: 2021-04-19 14:36:13.629853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fafc3dde8627'
down_revision = '345f470eba7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('address_building_number_key', 'address', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('address_building_number_key', 'address', ['building_number'])
    # ### end Alembic commands ###
