"""fix/ cascade appointments

Revision ID: ffe875017cea
Revises: fafc3dde8627
Create Date: 2021-04-22 21:49:15.871132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe875017cea'
down_revision = 'fafc3dde8627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('appointments_barber_shop_id_fkey', 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'barber_shop', ['barber_shop_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key('appointments_barber_shop_id_fkey', 'appointments', 'barber_shop', ['barber_shop_id'], ['id'])
    # ### end Alembic commands ###
